# Generated by Django 5.2.1 on 2025-05-09 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('adresse_mac', models.JSONField(default=list)),
                ('machine_type', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=50)),
                ('node_name', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=255)),
                ('os_release', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('machine_arch', models.CharField(max_length=50)),
                ('processor_name', models.CharField(max_length=100)),
                ('cpu_type', models.CharField(max_length=100)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_logical_cores', models.IntegerField()),
                ('cpu_frequency', models.FloatField(blank=True, null=True)),
                ('total_memory', models.BigIntegerField()),
                ('screen_resolution', models.CharField(max_length=50)),
                ('total_disk', models.BigIntegerField()),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_max_utilisation', models.IntegerField(default=100)),
                ('ram_max_utilisation', models.IntegerField(default=100)),
                ('priorite_min_acceptee', models.IntegerField(default=0)),
                ('duree_max_execution', models.IntegerField(default=0)),
                ('notification_email', models.BooleanField(default=False)),
                ('pauseActiviteUser', models.BooleanField(default=False)),
                ('playInactiviteUser', models.IntegerField(default=0)),
                ('types_calcul_autorises', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Préférence',
                'verbose_name_plural': 'Préférences',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='EtatMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_memory', models.BigIntegerField()),
                ('memory_usage', models.FloatField()),
                ('cache', models.BigIntegerField()),
                ('swap_total', models.BigIntegerField()),
                ('swap_used', models.BigIntegerField()),
                ('swap_percentage', models.FloatField()),
                ('used_disk', models.BigIntegerField()),
                ('disk_percentage', models.FloatField()),
                ('cpu_usage_per_core', models.JSONField()),
                ('gpu_usage_percentage', models.FloatField()),
                ('cpu_temperature', models.FloatField()),
                ('net_bytes_sent', models.BigIntegerField()),
                ('net_bytes_received', models.BigIntegerField()),
                ('battery_percentage', models.FloatField()),
                ('uptime', models.BigIntegerField()),
                ('boot_time', models.DateTimeField()),
                ('shutdown_time', models.DateTimeField(blank=True, null=True)),
                ('internet_enabled', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('statut_actuel', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='volontaire.machineinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PlageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plages', to='volontaire.jourdisponible')),
            ],
        ),
        migrations.AddField(
            model_name='jourdisponible',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='volontaire.preferencemodel'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, null=True)),
                ('dependencies', models.JSONField(blank=True, null=True)),
                ('execution_priority', models.IntegerField(default=0)),
                ('estimated_execution_time', models.IntegerField(blank=True, null=True)),
                ('actual_execution_time', models.IntegerField(blank=True, null=True)),
                ('input_data_size', models.IntegerField(blank=True, null=True)),
                ('output_data_size', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checkpoints', models.JSONField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('docker_information', models.JSONField(blank=True, null=True)),
                ('container_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volontaire.workflow')),
            ],
        ),
    ]
