# Generated by Django 4.2.21 on 2025-06-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0004_workflow_workflow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinfo',
            name='volunteer_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
