"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# CONFIGURATION MULTI-INSTANCES
# ============================================================================
# Permet de lancer plusieurs volontaires sur la même machine
# Variables d'environnement supportées:
#   - VOLUNTEER_PORT: Port du serveur (défaut: 8003)
#   - VOLUNTEER_INSTANCE_ID: Identifiant unique de l'instance
#   - VOLUNTEER_DATA_DIR: Répertoire de données personnalisé
# ============================================================================

VOLUNTEER_PORT = int(os.environ.get('VOLUNTEER_PORT', 8003))
VOLUNTEER_INSTANCE_ID = os.environ.get('VOLUNTEER_INSTANCE_ID', '')

# Générer un suffixe pour les fichiers si une instance est spécifiée
def _get_instance_suffix():
    if VOLUNTEER_INSTANCE_ID:
        return f"_{VOLUNTEER_INSTANCE_ID}"
    if VOLUNTEER_PORT != 8003:
        return f"_{VOLUNTEER_PORT}"
    return ""

INSTANCE_SUFFIX = _get_instance_suffix()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r)^fni=s(w%(e4hs-_jl*!7w6r^&eg1e-17fvx=!*g(s6p+78e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ajoute ici les apps du projet
    'volontaire',
    'channels',
    'socket_service',
    'redis_communication.apps.RedisAppConfig',
    'rest_framework',
]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 'volontaire/templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

ASGI_APPLICATION = 'backend.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# La base de données est dans data{INSTANCE_SUFFIX}/ pour supporter les instances multiples
# Chaque instance a sa propre base de données SQLite
DATA_DIR = BASE_DIR / f'data{INSTANCE_SUFFIX}'
DATA_DIR.mkdir(parents=True, exist_ok=True)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,  # Augmente le délai d'attente pour les connexions à la base de données
            'check_same_thread': False,  # Permet l'accès à la base de données depuis plusieurs threads
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration Redis
# Utiliser une variable d'environnement pour l'hôte du coordinator (défaut: 173.249.38.251)
REDIS_PROXY_HOST = os.environ.get('COORDINATOR_HOST', '173.249.38.251')  # Hôte du proxy Redis
REDIS_PROXY_PORT = int(os.environ.get('COORDINATOR_PROXY_PORT', '6380'))
REDIS_DB = 0


# Charger les paramètres spécifiques au proxy Redis dans l'environnement
os.environ.setdefault('COORDINATOR_HOST', REDIS_PROXY_HOST)

# Configuration du runtime vc-uyr (remplace Docker comme couche d'exécution)
RUNTIME_URL = os.environ.get('RUNTIME_URL', 'http://localhost:7070')
RUNTIME_HEALTH_TIMEOUT = int(os.environ.get('RUNTIME_HEALTH_TIMEOUT', '5'))