# Generated by Django 4.2.11 on 2025-05-22 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatmachine',
            name='battery_percentage',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='boot_time',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='disk_percentage',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='gpu_usage_percentage',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='internet_enabled',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='shutdown_time',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='swap_percentage',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='swap_total',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='used_disk',
        ),
        migrations.RemoveField(
            model_name='etatmachine',
            name='used_memory',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='cpu_cores',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='cpu_frequency',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='cpu_logical_cores',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='machine_arch',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='node_name',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='processor_name',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='system',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='total_disk',
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='total_memory',
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='battery',
            field=models.JSONField(blank=True, default=dict, help_text='Informations sur la batterie', null=True),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='cache_used',
            field=models.BigIntegerField(blank=True, default=0, help_text='Mémoire cache utilisée en octets', null=True),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='cache_used_human',
            field=models.CharField(blank=True, help_text='Mémoire cache utilisée en format lisible', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='cpu_usage_global',
            field=models.FloatField(default=0, help_text='Utilisation globale du CPU en pourcentage'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='disk_percent_free',
            field=models.FloatField(default=0, help_text='Pourcentage de disque libre'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='disk_percent_used',
            field=models.FloatField(default=0, help_text="Pourcentage d'utilisation du disque"),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='gpu_usage',
            field=models.JSONField(blank=True, default=list, help_text='Utilisation du GPU', null=True),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='internet_connected',
            field=models.BooleanField(default=False, help_text='Connexion Internet active'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_bytes_received_human',
            field=models.CharField(default='0', help_text='Octets reçus en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_bytes_sent_human',
            field=models.CharField(default='0', help_text='Octets envoyés en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_drop_in',
            field=models.IntegerField(default=0, help_text='Paquets supprimés en réception'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_drop_out',
            field=models.IntegerField(default=0, help_text='Paquets supprimés en envoi'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_errors_in',
            field=models.IntegerField(default=0, help_text='Erreurs en réception'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_errors_out',
            field=models.IntegerField(default=0, help_text='Erreurs en envoi'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_packets_received',
            field=models.BigIntegerField(default=0, help_text='Paquets reçus'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='net_packets_sent',
            field=models.BigIntegerField(default=0, help_text='Paquets envoyés'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='process_count',
            field=models.IntegerField(default=1, help_text='Nombre de processus actifs'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='ram_available',
            field=models.BigIntegerField(default=0, help_text='Mémoire RAM disponible en octets'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='ram_available_human',
            field=models.CharField(default='0', help_text='Mémoire RAM disponible en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='ram_percent_free',
            field=models.FloatField(default=0, help_text='Pourcentage de RAM libre'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='ram_percent_used',
            field=models.FloatField(default=0, help_text="Pourcentage d'utilisation de la RAM"),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='ram_used',
            field=models.BigIntegerField(default=0, help_text='Mémoire RAM utilisée en octets'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='ram_used_human',
            field=models.CharField(default='0', help_text='Mémoire RAM utilisée en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données brutes collectées', null=True),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='swap_free',
            field=models.BigIntegerField(default=0, help_text='Mémoire swap libre en octets'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='swap_free_human',
            field=models.CharField(default='0', help_text='Mémoire swap libre en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='swap_percent_free',
            field=models.FloatField(default=0, help_text='Pourcentage de swap libre'),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='swap_percent_used',
            field=models.FloatField(default=0, help_text="Pourcentage d'utilisation du swap"),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='swap_used_human',
            field=models.CharField(default='0', help_text='Mémoire swap utilisée en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='threshold_reached',
            field=models.JSONField(blank=True, default=dict, help_text="Seuils d'utilisation des ressources atteints", null=True),
        ),
        migrations.AddField(
            model_name='etatmachine',
            name='uptime_seconds',
            field=models.BigIntegerField(default=0, help_text='Temps de fonctionnement en secondes'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='bios_info',
            field=models.JSONField(blank=True, default=dict, help_text='Informations sur le BIOS', null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='cpu_architecture',
            field=models.CharField(default='', help_text='Architecture du processeur', max_length=50),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='cpu_bits',
            field=models.CharField(default='', help_text='Nombre de bits du processeur (32-bit, 64-bit)', max_length=10),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='cpu_cores_logical',
            field=models.IntegerField(default=1, help_text='Nombre de cœurs logiques'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='cpu_cores_physical',
            field=models.IntegerField(default=1, help_text='Nombre de cœurs physiques'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='cpu_frequency_current',
            field=models.FloatField(blank=True, help_text='Fréquence actuelle du processeur en MHz', null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='cpu_frequency_max',
            field=models.FloatField(blank=True, help_text='Fréquence maximale du processeur en MHz', null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='cpu_frequency_min',
            field=models.FloatField(blank=True, help_text='Fréquence minimale du processeur en MHz', null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='disk_total',
            field=models.BigIntegerField(default=0, help_text='Espace disque total en octets'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='disk_total_human',
            field=models.CharField(default='0', help_text='Espace disque total en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='hostname',
            field=models.CharField(default='', help_text="Nom d'hôte de la machine", max_length=255),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='logged_users',
            field=models.JSONField(default=list, help_text='Liste des utilisateurs connectés'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='motherboard_info',
            field=models.JSONField(blank=True, default=dict, help_text='Informations sur la carte mère', null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='network_interfaces',
            field=models.JSONField(default=list, help_text='Liste des interfaces réseau'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='os_architecture',
            field=models.CharField(default='', help_text="Architecture du système d'exploitation", max_length=50),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='os_name',
            field=models.CharField(default='', help_text="Nom du système d'exploitation", max_length=50),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='partitions',
            field=models.JSONField(default=list, help_text='Liste des partitions de disque'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='ram_total',
            field=models.BigIntegerField(default=0, help_text='Mémoire RAM totale en octets'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='ram_total_human',
            field=models.CharField(default='0', help_text='Mémoire RAM totale en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données brutes collectées', null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='swap_total',
            field=models.BigIntegerField(default=0, help_text='Mémoire swap totale en octets'),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='swap_total_human',
            field=models.CharField(default='0', help_text='Mémoire swap totale en format lisible', max_length=20),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='usb_devices',
            field=models.JSONField(blank=True, default=list, help_text='Liste des périphériques USB', null=True),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='available_days',
            field=models.JSONField(default=list, help_text='Jours de disponibilité (0-6, 0=lundi)'),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='available_hours_end',
            field=models.TimeField(blank=True, help_text='Heure de fin de disponibilité', null=True),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='available_hours_start',
            field=models.TimeField(blank=True, help_text='Heure de début de disponibilité', null=True),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='collection_interval',
            field=models.IntegerField(default=60, help_text='Intervalle de collecte des données en secondes'),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='disk_max_utilisation',
            field=models.IntegerField(default=90, help_text='Utilisation maximale du disque en pourcentage'),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='machine',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='volontaire.machineinfo'),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='notify_on_resource_threshold',
            field=models.BooleanField(default=True, help_text="Notifier lorsqu'un seuil de ressource est atteint"),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='notify_on_task_assignment',
            field=models.BooleanField(default=True, help_text="Notifier lors de l'assignation d'une tâche"),
        ),
        migrations.AddField(
            model_name='preferencemodel',
            name='send_interval',
            field=models.IntegerField(default=300, help_text="Intervalle d'envoi des données en secondes"),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='cpu_temperature',
            field=models.FloatField(blank=True, help_text='Température du CPU en degrés Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='cpu_usage_per_core',
            field=models.JSONField(default=list, help_text='Utilisation du CPU par cœur'),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='net_bytes_received',
            field=models.BigIntegerField(default=0, help_text='Octets reçus'),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='net_bytes_sent',
            field=models.BigIntegerField(default=0, help_text='Octets envoyés'),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='statut_actuel',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', help_text='Statut actuel du volontaire', max_length=10),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='swap_used',
            field=models.BigIntegerField(default=0, help_text='Mémoire swap utilisée en octets'),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Horodatage de la collecte'),
        ),
        migrations.AlterField(
            model_name='etatmachine',
            name='uptime',
            field=models.CharField(default='0', help_text='Temps de fonctionnement', max_length=50),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='adresse_mac',
            field=models.JSONField(default=list, help_text='Liste des adresses MAC de la machine'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='cpu_type',
            field=models.CharField(default='', help_text='Type de processeur', max_length=100),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Dernière mise à jour des informations'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='machine_type',
            field=models.CharField(default='', help_text='Type de machine (Portable, PC de bureau, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='os_release',
            field=models.CharField(default='', help_text="Release du système d'exploitation", max_length=100),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='os_version',
            field=models.CharField(default='', help_text="Version du système d'exploitation", max_length=100),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'enregistrement de la machine"),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='screen_resolution',
            field=models.CharField(default='', help_text="Résolution de l'écran", max_length=50),
        ),
        migrations.AlterField(
            model_name='preferencemodel',
            name='cpu_max_utilisation',
            field=models.IntegerField(default=80, help_text='Utilisation maximale du CPU en pourcentage'),
        ),
    ]
