# Generated by Django 4.2.11 on 2025-05-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0002_remove_etatmachine_battery_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('progress_type', models.CharField(choices=[('start', 'Démarrage'), ('progress', 'Progression'), ('complete', 'Terminée'), ('error', 'Erreur'), ('cancel', 'Annulée')], max_length=20)),
                ('percentage', models.FloatField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='volontaire.task')),
            ],
            options={
                'verbose_name': 'Progression de tâche',
                'verbose_name_plural': 'Progressions de tâches',
                'ordering': ['timestamp'],
            },
        ),
    ]
