# Generated by Django 4.2.11 on 2025-05-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0003_add_taskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='workflow_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
