# Generated by Django 4.2.11 on 2025-06-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0005_alter_machineinfo_volunteer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineinfo',
            name='password',
            field=models.CharField(default='', help_text='Mot de passe', max_length=255),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='username',
            field=models.CharField(default='', help_text="Nom d'utilisateur", max_length=255),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='volunteer_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
