# Generated by Django 5.2.3 on 2025-12-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0006_machineinfo_password_machineinfo_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemodel',
            name='machine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='volontaire.machineinfo'),
        ),
    ]
