# Generated by Django 5.2.3 on 2025-12-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0007_alter_preferencemodel_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineinfo',
            old_name='machine_type',
            new_name='machine_tipe',
        ),
    ]
