# Generated by Django 4.2.27 on 2026-01-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0009_rename_cpu_type_machineinfo_cpu_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='local_input_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
