# Generated by Django 4.2.7 on 2025-11-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("volontaire", "0006_machineinfo_password_machineinfo_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferencemodel",
            name="duree_max_execution",
            field=models.IntegerField(
                default=0, help_text="Durée maximale d'exécution en minutes"
            ),
        ),
        migrations.AlterField(
            model_name="preferencemodel",
            name="machine",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to="volontaire.machineinfo",
            ),
        ),
        migrations.AlterField(
            model_name="preferencemodel",
            name="notification_email",
            field=models.BooleanField(
                default=False, help_text="Activer les notifications par email"
            ),
        ),
        migrations.AlterField(
            model_name="preferencemodel",
            name="pauseActiviteUser",
            field=models.BooleanField(
                default=False, help_text="Pause lors de l'activité utilisateur"
            ),
        ),
        migrations.AlterField(
            model_name="preferencemodel",
            name="playInactiviteUser",
            field=models.IntegerField(
                default=0, help_text="Temps d'inactivité avant reprise (en minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="preferencemodel",
            name="priorite_min_acceptee",
            field=models.IntegerField(
                default=0, help_text="Priorité minimale acceptée pour les tâches"
            ),
        ),
        migrations.AlterField(
            model_name="preferencemodel",
            name="ram_max_utilisation",
            field=models.IntegerField(
                default=80, help_text="Utilisation maximale de la RAM en pourcentage"
            ),
        ),
        migrations.AlterField(
            model_name="preferencemodel",
            name="types_calcul_autorises",
            field=models.CharField(
                blank=True,
                help_text="Types de calcul autorisés",
                max_length=100,
                null=True,
            ),
        ),
    ]
