# Generated by Django 5.2.3 on 2025-12-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0008_rename_machine_type_machineinfo_machine_tipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineinfo',
            old_name='cpu_type',
            new_name='cpu_modele',
        ),
    ]
