# Generated by Django 4.2.27 on 2026-01-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontaire', '0010_add_local_input_path_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='command',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
